/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: stpzpG5BNdyk25ngDDeBjt
// Component: ibmeNGljcijm
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavBar from "../../NavBar"; // plasmic-import: 1LmBL71MUAXA/component
import Button from "../../Button"; // plasmic-import: RZcfRW_Hy_3y/component
import ProductCard from "../../ProductCard"; // plasmic-import: cE6JLoNudm3H/component
import Rating from "../../Rating"; // plasmic-import: olXKnGUR3tZq/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: o1V8se7u6UxM/component
import Value from "../../Value"; // plasmic-import: 7ilpMUuNUHHn/component
import Footer from "../../Footer"; // plasmic-import: fcMelusn795n/component
import { useScreenVariants as useScreenVariantszD8BVmAqArue } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zD8bVmAQArue/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: stpzpG5BNdyk25ngDDeBjt/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: ibmeNGljcijm/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: z1c60md6nL0O/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: X2-waAPW6lVe/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: I3sdioQxxOf4/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: hUXHU6IGDf7t/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: nFjeggxVLNXg/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: ffZm8LNF8pyZ/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("container42");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszD8BVmAqArue()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__uwxWw)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___8Dn6F)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iIbaA)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection!"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nxBvT
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </Stack__>
                <Button
                  className={classNames("__wab_instance", sty.button___7Q08V)}
                  end={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__xGmX)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cvlaH
                      )}
                    >
                      {"Shop"}
                    </div>
                  }
                  size={"extraLarge"}
                />
              </Stack__>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__nrfbM)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__cTb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t43X
                  )}
                >
                  {"Featured"}
                </div>
                <Stack__
                  as={PlasmicLink__}
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  hasGap={true}
                  className={classNames(projectcss.all, projectcss.a, sty.link)}
                  component={Link}
                  href={"#"}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6LsJt
                    )}
                  >
                    {"See more"}
                  </div>
                  <RightArrowIcon
                    className={classNames(projectcss.all, sty.svg__tTtD)}
                    role={"img"}
                  />
                </Stack__>
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___7E05Q
                )}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe14.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__nmMnh)}
                    rating={"four"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v93Zp
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eJwg
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___74LIm
                )}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe15.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__aw4Km)}
                    rating={"threeHalf"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mfbN
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2OYe6
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__fDdh)}
                dollars={"64"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe16.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__pWqrg)}
                    rating={"two"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6AAfc
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8OJ8
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__j64H)}
                dollars={"99"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe17.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating___3UuDt)}
                    rating={"four"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aVrO4
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lz4Kx
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___2T0Kn
                )}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe18.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__qZe0X)}
                    rating={"five"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eR1EX
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yRrJb
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__snFwX)}
                dollars={"65"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe19.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__xXunm)}
                    rating={"threeHalf"}
                  />
                }
              />
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__vMzi)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__o7FFa)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lfKjt)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tx7Jn)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pgMeS
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iQok5
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now\u2019s the perfect time to save on iconic shoes."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jOqXp)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fpiCu
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__iiFiU)}
                    end={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__e6DSr)}
                        role={"img"}
                      />
                    }
                    iconEnd={true}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9GCd
                        )}
                      >
                        {"Shop sale"}
                      </div>
                    }
                    size={"extraLarge"}
                  />
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          />

          <section className={classNames(projectcss.all, sty.section__qNsWs)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wDuZ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rhVy7
                      )}
                    >
                      {"Just added"}
                    </div>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__yIxYp
                      )}
                      component={Link}
                      href={"#"}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__crgeF
                        )}
                      >
                        {"See more"}
                      </div>
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg___2HbX)}
                        role={"img"}
                      />
                    </Stack__>
                  </div>
                ),

                value: args.container42
              })}
            </div>
            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wmBVl)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fLbb0
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8C1BP
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wolyn
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gMy06
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bxwTt
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8W833
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dtymz
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ttNZg
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9Vu7T
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__voajs
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qQhlK
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__alRs4
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__usQCw
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z1Soq
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ciIll
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                />
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__m0GtI)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__eKaaH)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aJfHt
                  )}
                >
                  {"Categories"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__moe4Y
                  )}
                >
                  {"All"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nkr9J
                  )}
                >
                  {"New"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hjnt2
                  )}
                >
                  {"Womens"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Bg1V
                  )}
                >
                  {"Mens"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y6P0M
                  )}
                >
                  {"Kids"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__stWbE
                  )}
                >
                  {"On sale"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zIZ)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__uhZkA
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jfTqw
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zOaIk
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__a811I
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dN1Yt
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jEhh4
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vl7Ot
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y8PM6
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qe20Z
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___2F957
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nSk36
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yDmjr
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rXbgU
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9T5Lv
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fwNes
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__x6QOp
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d1Ya5
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cLfog
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__x2EwS
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iihC
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4Zs8
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yIHxP
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1PA7Z
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Y8KS
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___9W2Em
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yyIDs
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rtLlp
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wpod1
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tCalS
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aFu3
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zkrpw
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g5Lrb
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__n23Bh
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nOCrG
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__v9B2Q
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3GBz
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </Stack__>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__vb3ET)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                className={classNames("__wab_instance", sty.value___1VdpM)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__vy5Xs)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wnxKe
                  )}
                >
                  {"Our goals"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zeS9S
                  )}
                >
                  {"We\u2019re learning how to become a new kind of company."}
                </div>
              </Value>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__ncL7L)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__za7Dv)}>
                <Value
                  className={classNames("__wab_instance", sty.value__srJtn)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__iiR7F)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g8REq
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cpyBx
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__teG2B)}>
                <Value
                  className={classNames("__wab_instance", sty.value__fImBn)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__mWWoW)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bFTuC
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p4HEt
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__eOlB)}>
                <Value
                  className={classNames("__wab_instance", sty.value__smk22)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__koHnw)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lHbMj
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yohhe
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__hxalQ)}>
                <Value
                  className={classNames("__wab_instance", sty.value__fpDhm)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__sJufq)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3TaX5
                    )}
                  >
                    {"We give back for every sale."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eMNm8
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>
                </Value>
              </div>
            </Stack__>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "link",
    "container",
    "emojiValueProps",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],

  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4", "link"],
  link: ["link"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    link: makeNodeComponent("link"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
